services:
  ys-monitor:
    build: ./ys_monitor
    container_name: ys-monitor
    command: ["python", "ys.py"]  # 启动数据监控器
    volumes:
      - ./logs/ys_monitor:/app/logs
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    network_mode: "host"

  bwenews-monitor:
    build: ./bwenews
    container_name: bwenews-monitor
    command: ["python", "main.py"]  # 启动数据监控器
    volumes:
      - ./logs/bwenews:/app/logs
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    network_mode: "host"

  alpha-monitor:
    build: ./alpha_monitor
    container_name: alpha-monitor
    command: ["python", "alpha.py"]  # 启动数据监控器
    volumes:
      - ./logs/alpha_monitor:/app/logs
      - ./alpha_monitor/alpha_monitor_state.json:/app/alpha_monitor_state.json
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    network_mode: "host"

  exchange-price-service:
    build: ./price_service
    container_name: exchange-price-service
    command: ["uvicorn", "price_service:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8123:8000"
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./logs/exchange_price:/app/logs